import {createRoom,buildAvatar} from './mce_3d_room.js';
const fans=Number(localStorage.getItem('mceFans'))||0,cash=Number(localStorage.getItem('mceCash'))||500,xp=Number(localStorage.getItem('mceXP'))||0;document.getElementById('fans').textContent=fans;document.getElementById('cash').textContent=cash;document.getElementById('xp').textContent=xp;
const room=createRoom({spawn:[0,1.7,8],background:0x08030d,fog:0x0b0410,fogDensity:.018,sky:0x7c3c91});room.wallBounds(24,22,5.5);room.label('AVATAR STUDIO',[0,4.5,-10.5],'#e05bff',[7,1.5]);
for(let x=-8;x<=8;x+=4)room.box('ceiling beam',[.18,.18,21],[x,5.1,0],0x2b202e,{metalness:.8});room.light(0xbb39ff,22,[-6,4,0],18);room.light(0x2ab9ff,18,[6,4,-2],18);room.light(0xffb52b,12,[0,4,7],15);
room.box('mirror wall',[8,3.6,.18],[0,2.1,-10.25],0x7790a0,{metalness:.95,roughness:.08});room.box('platform',[5,.25,4],[0,.12,-5],0x32183c,{collider:true});room.label('BUILD YOUR LOOK',[0,3.8,-10.05],'#ffd24a',[5.5,1]);
for(const x of [-8,-5,5,8]){room.box('wardrobe',[2.2,3.5,.8],[x,1.75,-8.8],0x241329,{collider:true});room.label(x<0?'FITS':'STYLE',[x,3.1,-8.32],'#ffffff',[1.5,.35])}
let avatarData=JSON.parse(localStorage.getItem('mceAvatar')||'null')||{name:'New Artist',type:'Rapper',skin:'#9a5f3c',hairStyle:'fade',hairColor:'#171016',shirtColor:'#7b2cff',pantsColor:'#171b2d'};let avatar=buildAvatar(room,avatarData,[0,.25,-5],1.08);room.label(avatarData.name.toUpperCase(),[0,3.8,-5],'#ffffff',[4,.75]);
const customizer=document.getElementById('customizer');room.interact('CUSTOMIZE 3D ARTIST',[0,1.7,-2.6],()=>{loadForm();customizer.classList.add('show')},3,0xd24bff);room.interact('ENTER BATTLE STAGE',[8.2,1.7,8.2],()=>{if(fans<25)alert('Word Slaughter requires 25 fans. You need '+(25-fans)+' more.');else location.href='battle_room.html'},2.6,0xff315b);room.interact('RETURN TO WAREHOUSE',[-8.2,1.7,8.2],()=>location.href='warehouse.html',2.6,0xffd24a);room.label('BATTLE STAGE',[8.2,2.8,10.5],'#ff315b',[3,.65]);room.label('WAREHOUSE',[-8.2,2.8,10.5],'#ffd24a',[3,.65]);
let skin=avatarData.skin;const ids=['artistName','artistType','hairStyle','hairColor','shirtColor','pantsColor'];function loadForm(){ids.forEach(id=>{const el=document.getElementById(id),key=id==='artistName'?'name':id;el.value=avatarData[key]||el.value});skin=avatarData.skin}
document.querySelectorAll('[data-skin]').forEach(b=>b.onclick=()=>skin=b.dataset.skin);document.getElementById('saveAvatar').onclick=()=>{avatarData={name:document.getElementById('artistName').value.trim()||'New Artist',type:document.getElementById('artistType').value,hairStyle:document.getElementById('hairStyle').value,hairColor:document.getElementById('hairColor').value,shirtColor:document.getElementById('shirtColor').value,pantsColor:document.getElementById('pantsColor').value,skin};localStorage.setItem('mceAvatar',JSON.stringify(avatarData));room.scene.remove(avatar);avatar=buildAvatar(room,avatarData,[0,.25,-5],1.08);document.getElementById('notice').textContent='✓ 3D artist saved. Your look will appear on the battle stage.'};document.getElementById('closeCustomizer').onclick=()=>customizer.classList.remove('show');
