import {createRoom,buildAvatar} from './mce_3d_room.js';
let fans=Number(localStorage.getItem('mceFans'))||0,cash=Number(localStorage.getItem('mceCash'))||500,xp=Number(localStorage.getItem('mceXP'))||0;const stat=()=>{document.getElementById('fans').textContent=fans;document.getElementById('cash').textContent=cash;document.getElementById('xp').textContent=xp};stat();
if(fans<25){alert('Word Slaughter requires 25 fans. Customize your artist now, then return when the stage unlocks.');location.replace('avatar_studio.html')}
const room=createRoom({spawn:[0,1.7,11],background:0x030205,fog:0x090207,fogDensity:.017,sky:0x5c2135});room.wallBounds(36,30,7);room.label('WORD SLAUGHTER',[0,5.8,-14.45],'#ff315b',[12,2.2]);room.label('REAL BARS • REAL TALENT • NO LIMITS',[0,4.55,-14.4],'#ffd258',[9,.65]);
room.box('stage',[18,.8,8],[0,.4,-8.5],0x1b1017,{collider:true,metalness:.2});room.box('stage trim',[18.3,.25,.25],[0,.72,-4.55],0xff174d,{metalness:.5});room.box('dj booth',[5,1.5,1.5],[0,1.55,-12],0x17101b,{collider:true});room.label('D-A WAREHOUSE',[0,2.55,-11.2],'#ff315b',[4,.7]);
for(const x of [-8,8]){room.box('speaker',[2,4,1.5],[x,2.2,-11.8],0x0b0b0d,{collider:true});for(let y=.9;y<3.8;y+=1.3)room.cylinder('speaker cone',.42,.08,[x,y,-11],0x29262d).rotation.x=Math.PI/2}
for(let x=-14;x<=14;x+=4)room.box('truss',[.16,.16,28],[x,6.2,-1],0x443b45,{metalness:.9});for(const [x,c] of [[-8,0xff174d],[-3,0xaa2cff],[3,0x2f86ff],[8,0xff174d]])room.light(c,28,[x,6,-6],22);
const av=JSON.parse(localStorage.getItem('mceAvatar')||'null')||{name:'New Artist'};buildAvatar(room,av,[-3,.82,-8],1);buildAvatar(room,{skin:'#6a3f28',hairStyle:'afro',hairColor:'#101010',shirtColor:'#d7193f',pantsColor:'#111111'},[3,.82,-8],1);room.label((av.name||'NEW ARTIST').toUpperCase(),[-3,4.3,-8],'#ffffff',[3,.55]);room.label('KNOCKOUT KAI',[3,4.3,-8],'#ffb1bd',[3,.55]);
for(let z=-2;z<=9;z+=2.4)for(let x=-13;x<=13;x+=2.3){if(Math.abs(x)<2&&z<1)continue;const g=room.cylinder('crowd',.25,1.3,[x,.65,z],['#43233a','#22324a','#4a2f24'][Math.floor(Math.random()*3)]),h=room.cylinder('head',.2,.35,[x,1.48,z],['#5a341f','#9a5f3c','#c78962'][Math.floor(Math.random()*3)]);room.animated.push(t=>{g.position.y=.65+Math.sin(t*.003+x+z)*.05;h.position.y=1.48+Math.sin(t*.003+x+z)*.05})}
room.box('battle circle',[7,.05,4],[0,.84,-7.2],0x350b19);room.interact('ENTER BATTLE CIRCLE',[0,1.7,-3.8],()=>document.getElementById('battlePanel').classList.add('show'),3.2,0xff315b);room.interact('AVATAR ROOM',[13.5,1.7,11.5],()=>location.href='avatar_studio.html',2.6,0xd24bff);room.interact('WAREHOUSE LOBBY',[-13.5,1.7,11.5],()=>location.href='warehouse.html',2.6,0xffd24a);room.label('AVATAR ROOM',[13.5,3,14.4],'#d24bff',[3,.6]);room.label('LOBBY',[-13.5,3,14.4],'#ffd24a',[2.5,.6]);
const battlePanel=document.getElementById('battlePanel'),energy=document.getElementById('energy'),battleLog=document.getElementById('battleLog'),roundText=document.getElementById('roundText'),startBattle=document.getElementById('startBattle');let round=0,score=0,active=false;const buttons=[...document.querySelectorAll('[data-action]')],lines={bars:['A sharp punchline shakes the front row.','The judges react to the wordplay.'],flow:['You switch cadence and catch Kai off guard.','The new pocket pulls the room in.'],crowd:['The Warehouse throws its hands up.','Your call-and-response fills the room.']};function enable(v){buttons.forEach(b=>b.disabled=!v)}startBattle.onclick=()=>{round=1;score=0;active=true;energy.style.width='8%';roundText.textContent='Round 1 of 3';battleLog.textContent='The DJ drops the beat. The circle closes around the artists.';enable(true);startBattle.disabled=true};buttons.forEach(b=>b.onclick=()=>{if(!active)return;const type=b.dataset.action,gain=12+Math.floor(Math.random()*17);score+=gain;energy.style.width=Math.min(score,100)+'%';battleLog.textContent=lines[type][Math.floor(Math.random()*2)]+' +'+gain+' crowd energy.';if(round===3){active=false;enable(false);const opp=48+Math.floor(Math.random()*28);if(score>=opp){fans+=20;cash+=100;xp+=25;battleLog.innerHTML='<b style="color:#77ffac">🏆 YOU WON WORD SLAUGHTER!</b><br>+20 Fans • +$100 • +25 XP'}else{xp+=8;battleLog.textContent='Knockout Kai takes this battle. You earn +8 XP and can challenge again.'}localStorage.setItem('mceFans',fans);localStorage.setItem('mceCash',cash);localStorage.setItem('mceXP',xp);stat();startBattle.disabled=false;startBattle.textContent='BATTLE AGAIN'}else{round++;roundText.textContent='Round '+round+' of 3'}});document.getElementById('closeBattle').onclick=()=>battlePanel.classList.remove('show');
